name: RUSTSEC Bot
description: 'Creates issues from RUSTSEC advisories'

inputs:
  labels:
    description: |
      Comma-separated list of labels to add to the issue.
    required: true
    default: rust,security

  token:
    description: |
      GitHub token with the 'issues:write' scope
    required: true
    default: ${{ github.token }}

outputs:
  opened:
    description: 'List of issues/advisories that were opened'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/olix0r/rustsecbot:v1'
  # image: 'Dockerfile'
  args:
    - --github-token
    - ${{ inputs.token }}
    - --labels
    - ${{ inputs.labels }}
