name: RUSTSEC Bot
description: 'Creates issues from RUSTSEC advisories'

inputs:
  config:
    description: |
      RustSecBot configuration file
    required: true
    default: .github/rustsecbot.yml

  token:
    description: |
      GitHub token with the 'issues:write' scope
    required: true
    default: ${{ github.token }}

outputs:
  opened:
    description: 'List of issues/advisories that were opened'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/olix0r/rustsecbot:v1'
  # image: 'Dockerfile'
  args:
    - --config=${{ inputs.config }}
    - --github-token=${{ inputs.token }}
