name: RUSTSEC Bot
description: 'Creates issues from RUSTSEC advisories'

# TODO:
# - Custom labels
inputs:
  token:
    description: |
      GitHub token with 'issues:write' scope
    required: true
    default: ${{ github.token }}

outputs:
  opened:
    description: 'List of issues/advisories that were opened'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/olix0r/rustsecbot:v1'
  # image: 'Dockerfile'
  args:
    - --github-token=${{ inputs.token }}
