name: RUSTSEC Bot
description: 'Creates issues from RUSTSEC advisories'

# TODO:
# - Custom labels
inputs: {}

outputs:
  opened:
    description: 'List of issues/advisories that were opened'

runs:
  using: 'docker'
  # TODO image: 'docker://ghcr.io/olix0r/rustsecbot:v1'
  image: 'Dockerfile'
  args:
    - --github-token="${{ secrets.GITHUB_TOKEN }}"
