[package]
name = "rustsec-issues"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt", "macros", "time"] }

[dependencies.clap]
version = "3"
default-features = false
features = ["cargo", "derive", "env", "std"]

[dependencies.hubcaps]
version = "0.6"
git = "https://github.com/olix0r/hubcaps.git"
branch = "ver/feature-jwt"
