name: RUSTSEC

on:
  push:
    branches:
      - main
  schedule:
    cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  rustsecbot:
    timeout-minutes: 10
    uses: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - uses: olix0r/rustsecbot@v1
