name: RUSTSEC

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - action.yml
      - .github/workflows/rustsec.yml
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write

jobs:
  rustsecbot:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - uses: ./
